# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 16:11
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ardentreader', '0006_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='ardentreader.BlogCategory'),
        ),
    ]
